version: '2'

services:
  as-stats:
    image: archaron/as-stats-ng
    ports:
      - "8080:80"
      - "5000:5000/udp"
    environment:
      - NETFLOW=1
      - NETFLOW_PORT=5000
      - TZ=Europe/Moscow
    volumes:
      - ./as-stats:/data/as-stats